"""guild settings

Revision ID: 71cda180a072
Revises: 
Create Date: 2022-09-18 09:24:39.211212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cda180a072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guildsettings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('privileged_command_role_id', sa.BigInteger(), nullable=True),
    sa.Column('voice_scalar_category_id', sa.BigInteger(), nullable=True),
    sa.Column('voice_scalar_default_name', sa.String(length=30), nullable=True),
    sa.Column('rolebot_settings_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('autorole',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guildsettings.guild_id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autorole')
    op.drop_table('guildsettings')
    # ### end Alembic commands ###
