--- 
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: clanbotjas-pv
spec: 
  accessModes: 
    - ReadWriteMany
  capacity: 
    storage: 10Mi
  nfs: 
    path: /mnt/path/to/clanbotjas
    server: "<nfs-server-ip-here>"
  persistentVolumeReclaimPolicy: Retain