name: Docker Image CI

on:
  push:
    branches:
      - 'master'
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout    
      uses: actions/checkout@v3
    -
      name: Docker Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: clanbadjas/clanbotjas
    - 
      name: Docker Login
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Docker Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
