name: Docker Image CI dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Docker Build
      run: docker build . --file Dockerfile --tag clanbadjas/clanbotjas-dev:latest
    
    - name: Docker Push latest tag
      run: docker push clanbadjas/clanbotjas-dev:latest
